[package]
name = "get_nonce_test_contracts"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[lib]

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.9.2"