[package]
name = "units-e2e-tests"
homepage.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
reqwest.workspace = true
tokio.workspace = true
once_cell = "1.19"
starknet = "0.9"
url = "2.5"
uuid.workspace = true

[lints]
workspace = true
