name: Task - Lint Cargo

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cargo-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup the environment with all necessary dependencies
      - uses: ./.github/actions/load-env

      # Setup the rust environment
      - uses: ./.github/actions/setup
        with:
          cache-key: ${{ env.BUILD_RUST_CACHE_KEY }}
          rust-version: ${{ env.BUILD_RUST_VERSION }}
          install-mold: false
          install-scarb: false

      - name: Units Engine Format and clippy
        run: |
          cargo fmt -- --check
          cargo clippy --workspace --no-deps -- -D warnings
          cargo clippy --workspace --tests --no-deps -- -D warnings
